default_platform(:ios)

platform :ios do
  desc "Get certificates for ios project"
  lane :certificates do |options|
    readonly = options[:readonly] || true
    match(readonly: readonly)
    match(type: 'appstore', readonly: readonly)
  end
end
