default_platform(:ios)

platform :ios do
  desc "Get certificates for ios project"
  lane :certificates do |options|
    readonly = options[:readonly] || true
    match(readonly: readonly)
    match(type: 'appstore', readonly: readonly)
  end

  desc "Upload version to Testflight"
  lane :beta do
    cocoapods()
    sync_code_signing(type: "appstore", readonly: true)
    build_app(scheme: "ReactNativePlayground")
    upload_to_testflight
  end
end
